vich_uploader:
    db_driver: orm

    mappings:
        galerie_image:
            uri_prefix : /images/galeries
            upload_destination : '%kernel.project_dir%/public/images/galeries'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        picture_imagefile :
            uri_prefix : /images/galeries
            upload_destination : '%kernel.project_dir%/public/images/galeries'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'


